### PR TITLE
Added capital ligatures

### PR DESCRIPTION
**Pull request by kovacshviktor**
On branch add_capital_ligatures
 Changes to be committed:
	modified:   documentation/NotoSansOldHungarian.article.html
	modified:   sources/NotoSansOldHungarian.glyphs

### CODE REVIEW

**Comment by kovacshviktor** [comment]
This MR adds the uppercase ligatures that were missing in the previous implementation. It brings the upper and lower case letters to a baseline. The electronic library of the National Széchenyi Library has ~50 books with single-baseline text. (https://mek.oszk.hu/) Rovas-info is the only publisher that aligns letters to the centerline (~10 books) This MR does not include the accented display, which appears in correspondence of 2-3 people only in the 20th century. The alphabet of the latter uses several incorrect letters ("Y" shaped B, "triangle" shaped O...)
This MR resolves #15 and #16 issues
Issues #1 and #2 do not belong to this repo.
This MR optimises the use of ligatures in such a way that only consonant + vowel ligatures are included in the discrete ligatures, otherwise the automatism may render the text unreadable. The ligatures "JI", "VV", "KV" and "KSZ" are not included in the discrete ligatures either, because they are reserved for "Y", "W", "Qu" and "X".

**Comment by kovacshviktor** [comment]
@simoncozens  Plesae merge this MR!

**Comment by kovacshviktor** [comment]
@simoncozens I did not redraw the whole font, my font designer just saved the glyphs file in a different structure.

**Comment by kovacshviktor** [comment]
@simoncozens The submission  [21-115](https://www.unicode.org/L2/L2021/21115-old-hungarian.pdf) to Unicode was not accepted building on the following submissions: [22-285](https://www.unicode.org/L2/L2022/22285-old-hungarian.pdf) , [23-067](https://www.unicode.org/L2/L2023/23067-hungarian-response.pdf) [24-003](https://www.unicode.org/L2/L2024/24003-old-hungarian-summary.pdf) .
The decision-makers are Michael Everson and André Szabolcs Szelp.

**Comment by kovacshviktor** [comment]
@simoncozens What does it mean "add more commits"?
I need to add more ligatures?

**Comment by simoncozens** [comment]
Strange to change the article just to add ligatures, no?

**Comment by kovacshviktor** [comment]
> Strange to change the article just to add ligatures, no?

The  On the main discussion page, which has been frozen, was the need for ligatures in capital letters. There was also a request to align the upper and lower case letters to a baseline. What I added was to optimize the ligatures according to our experience.

**Comment by simoncozens** [comment]
This PR also:

* Adds a change to the article.
* Changes the font family name from `Noto Sans Old Hungarian` to `Noto Sans Old Hungarian Regular`. "Regular" does not belong in the family name.
* Changes all the glyph outlines to use quadratic curves. Font *sources* should use cubic curves.
* Changed the size of the numerals.
* The kerning of the new ligatures is written in feature code, rather than in the font's kerning source tables.

I don't know whether adding all these ligatures is a good idea or not - but I can't accept this PR as it stands because of what it does to the rest of the source file.

**Comment by kovacshviktor** [comment]
> This PR also:
> 
> * Adds a change to the article.
> * Changes the font family name from `Noto Sans Old Hungarian` to `Noto Sans Old Hungarian Regular`. "Regular" does not belong in the family name.

It's my fault.

> * Changes all the glyph outlines to use quadratic curves. Font _sources_ should use cubic curves.

Sorry, fonforge changed it.

> * Changed the size of the numerals.

Yes. The Rovas Foundation's request was also on the original discussion paper.

> * The kerning of the new ligatures is written in feature code, rather than in the font's kerning source tables.
> 

Sorry, I used the FontForge. I am not a perfect developer. I  wanted to resolve this quickly.

> I don't know whether adding all these ligatures is a good idea or not - but I can't accept this PR as it stands because of what it does to the rest of the source file.

All right, I'll try to ask someone to prepare it.

**Comment by kovacshviktor** [comment]
@simoncozens I'll work with it.

**Comment by kovacshviktor** [comment]
@simoncozens Leave the usability experience to us. We are Hungarians, we can better see what needs to be touched, (in discrete describing) what does not. I close this PR.

**Pull request closed without merging**
